steps:
  # 1. Ejecutar pruebas unitarias o de sintaxis antes de compilar
  - name: 'python:3.10-slim'
    id: CI-Syntax-Check
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python -m py_compile main.py
        echo "Validación OK"

  # 2. Construir la imagen de Docker
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker-Build
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/mom-repo/agente-inventario:$COMMIT_SHA', '.']

  # 3. Subir (Push) la imagen a Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Docker-Push
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/mom-repo/agente-inventario:$COMMIT_SHA']

  # 4. Desplegar en Cloud Run (Actualiza automáticamente el servicio en vivo)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Cloud-Run-Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'agente-inventario-srv'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/mom-repo/agente-inventario:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# Para habilitar la recolección de las imágenes
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/mom-repo/agente-inventario:$COMMIT_SHA'

timeout: '900s'
options:
  logging: CLOUD_LOGGING_ONLY
